/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * An error response object.
 */
export type CreateImageResponseResponseBodyData = {
  /**
   * Error message describing the reason for failure.
   */
  message?: string | null | undefined;
};

/**
 * An error response object.
 */
export class CreateImageResponseResponseBody extends Error {
  /** The original data that was passed to this error instance. */
  data$: CreateImageResponseResponseBodyData;

  constructor(err: CreateImageResponseResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.name = "CreateImageResponseResponseBody";
  }
}

/**
 * An error response object.
 */
export type CreateImageResponseBodyData = {
  /**
   * Error message describing the reason for failure.
   */
  message?: string | null | undefined;
};

/**
 * An error response object.
 */
export class CreateImageResponseBody extends Error {
  /** The original data that was passed to this error instance. */
  data$: CreateImageResponseBodyData;

  constructor(err: CreateImageResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.name = "CreateImageResponseBody";
  }
}

/** @internal */
export const CreateImageResponseResponseBody$inboundSchema: z.ZodType<
  CreateImageResponseResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.nullable(z.string()).optional(),
})
  .transform((v) => {
    return new CreateImageResponseResponseBody(v);
  });

/** @internal */
export type CreateImageResponseResponseBody$Outbound = {
  message?: string | null | undefined;
};

/** @internal */
export const CreateImageResponseResponseBody$outboundSchema: z.ZodType<
  CreateImageResponseResponseBody$Outbound,
  z.ZodTypeDef,
  CreateImageResponseResponseBody
> = z.instanceof(CreateImageResponseResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.nullable(z.string()).optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateImageResponseResponseBody$ {
  /** @deprecated use `CreateImageResponseResponseBody$inboundSchema` instead. */
  export const inboundSchema = CreateImageResponseResponseBody$inboundSchema;
  /** @deprecated use `CreateImageResponseResponseBody$outboundSchema` instead. */
  export const outboundSchema = CreateImageResponseResponseBody$outboundSchema;
  /** @deprecated use `CreateImageResponseResponseBody$Outbound` instead. */
  export type Outbound = CreateImageResponseResponseBody$Outbound;
}

/** @internal */
export const CreateImageResponseBody$inboundSchema: z.ZodType<
  CreateImageResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.nullable(z.string()).optional(),
})
  .transform((v) => {
    return new CreateImageResponseBody(v);
  });

/** @internal */
export type CreateImageResponseBody$Outbound = {
  message?: string | null | undefined;
};

/** @internal */
export const CreateImageResponseBody$outboundSchema: z.ZodType<
  CreateImageResponseBody$Outbound,
  z.ZodTypeDef,
  CreateImageResponseBody
> = z.instanceof(CreateImageResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.nullable(z.string()).optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateImageResponseBody$ {
  /** @deprecated use `CreateImageResponseBody$inboundSchema` instead. */
  export const inboundSchema = CreateImageResponseBody$inboundSchema;
  /** @deprecated use `CreateImageResponseBody$outboundSchema` instead. */
  export const outboundSchema = CreateImageResponseBody$outboundSchema;
  /** @deprecated use `CreateImageResponseBody$Outbound` instead. */
  export type Outbound = CreateImageResponseBody$Outbound;
}
