/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ShortGeniusError } from "./shortgeniuserror.js";

/**
 * An error response object.
 */
export type DraftQuizVideoResponseResponseBodyData = {
  /**
   * Error message describing the reason for failure.
   */
  message?: string | null | undefined;
};

/**
 * An error response object.
 */
export class DraftQuizVideoResponseResponseBody extends ShortGeniusError {
  /** The original data that was passed to this error instance. */
  data$: DraftQuizVideoResponseResponseBodyData;

  constructor(
    err: DraftQuizVideoResponseResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "DraftQuizVideoResponseResponseBody";
  }
}

/**
 * An error response object.
 */
export type DraftQuizVideoResponseBodyData = {
  /**
   * Error message describing the reason for failure.
   */
  message?: string | null | undefined;
};

/**
 * An error response object.
 */
export class DraftQuizVideoResponseBody extends ShortGeniusError {
  /** The original data that was passed to this error instance. */
  data$: DraftQuizVideoResponseBodyData;

  constructor(
    err: DraftQuizVideoResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "DraftQuizVideoResponseBody";
  }
}

/** @internal */
export const DraftQuizVideoResponseResponseBody$inboundSchema: z.ZodType<
  DraftQuizVideoResponseResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.nullable(z.string()).optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new DraftQuizVideoResponseResponseBody(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type DraftQuizVideoResponseResponseBody$Outbound = {
  message?: string | null | undefined;
};

/** @internal */
export const DraftQuizVideoResponseResponseBody$outboundSchema: z.ZodType<
  DraftQuizVideoResponseResponseBody$Outbound,
  z.ZodTypeDef,
  DraftQuizVideoResponseResponseBody
> = z.instanceof(DraftQuizVideoResponseResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.nullable(z.string()).optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DraftQuizVideoResponseResponseBody$ {
  /** @deprecated use `DraftQuizVideoResponseResponseBody$inboundSchema` instead. */
  export const inboundSchema = DraftQuizVideoResponseResponseBody$inboundSchema;
  /** @deprecated use `DraftQuizVideoResponseResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    DraftQuizVideoResponseResponseBody$outboundSchema;
  /** @deprecated use `DraftQuizVideoResponseResponseBody$Outbound` instead. */
  export type Outbound = DraftQuizVideoResponseResponseBody$Outbound;
}

/** @internal */
export const DraftQuizVideoResponseBody$inboundSchema: z.ZodType<
  DraftQuizVideoResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.nullable(z.string()).optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new DraftQuizVideoResponseBody(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type DraftQuizVideoResponseBody$Outbound = {
  message?: string | null | undefined;
};

/** @internal */
export const DraftQuizVideoResponseBody$outboundSchema: z.ZodType<
  DraftQuizVideoResponseBody$Outbound,
  z.ZodTypeDef,
  DraftQuizVideoResponseBody
> = z.instanceof(DraftQuizVideoResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.nullable(z.string()).optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DraftQuizVideoResponseBody$ {
  /** @deprecated use `DraftQuizVideoResponseBody$inboundSchema` instead. */
  export const inboundSchema = DraftQuizVideoResponseBody$inboundSchema;
  /** @deprecated use `DraftQuizVideoResponseBody$outboundSchema` instead. */
  export const outboundSchema = DraftQuizVideoResponseBody$outboundSchema;
  /** @deprecated use `DraftQuizVideoResponseBody$Outbound` instead. */
  export type Outbound = DraftQuizVideoResponseBody$Outbound;
}
