/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * An error response object.
 */
export type DraftNewsVideoResponseResponseBodyData = {
  /**
   * Error message describing the reason for failure.
   */
  message?: string | null | undefined;
};

/**
 * An error response object.
 */
export class DraftNewsVideoResponseResponseBody extends Error {
  /** The original data that was passed to this error instance. */
  data$: DraftNewsVideoResponseResponseBodyData;

  constructor(err: DraftNewsVideoResponseResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.name = "DraftNewsVideoResponseResponseBody";
  }
}

/**
 * An error response object.
 */
export type DraftNewsVideoResponseBodyData = {
  /**
   * Error message describing the reason for failure.
   */
  message?: string | null | undefined;
};

/**
 * An error response object.
 */
export class DraftNewsVideoResponseBody extends Error {
  /** The original data that was passed to this error instance. */
  data$: DraftNewsVideoResponseBodyData;

  constructor(err: DraftNewsVideoResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.name = "DraftNewsVideoResponseBody";
  }
}

/** @internal */
export const DraftNewsVideoResponseResponseBody$inboundSchema: z.ZodType<
  DraftNewsVideoResponseResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.nullable(z.string()).optional(),
})
  .transform((v) => {
    return new DraftNewsVideoResponseResponseBody(v);
  });

/** @internal */
export type DraftNewsVideoResponseResponseBody$Outbound = {
  message?: string | null | undefined;
};

/** @internal */
export const DraftNewsVideoResponseResponseBody$outboundSchema: z.ZodType<
  DraftNewsVideoResponseResponseBody$Outbound,
  z.ZodTypeDef,
  DraftNewsVideoResponseResponseBody
> = z.instanceof(DraftNewsVideoResponseResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.nullable(z.string()).optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DraftNewsVideoResponseResponseBody$ {
  /** @deprecated use `DraftNewsVideoResponseResponseBody$inboundSchema` instead. */
  export const inboundSchema = DraftNewsVideoResponseResponseBody$inboundSchema;
  /** @deprecated use `DraftNewsVideoResponseResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    DraftNewsVideoResponseResponseBody$outboundSchema;
  /** @deprecated use `DraftNewsVideoResponseResponseBody$Outbound` instead. */
  export type Outbound = DraftNewsVideoResponseResponseBody$Outbound;
}

/** @internal */
export const DraftNewsVideoResponseBody$inboundSchema: z.ZodType<
  DraftNewsVideoResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.nullable(z.string()).optional(),
})
  .transform((v) => {
    return new DraftNewsVideoResponseBody(v);
  });

/** @internal */
export type DraftNewsVideoResponseBody$Outbound = {
  message?: string | null | undefined;
};

/** @internal */
export const DraftNewsVideoResponseBody$outboundSchema: z.ZodType<
  DraftNewsVideoResponseBody$Outbound,
  z.ZodTypeDef,
  DraftNewsVideoResponseBody
> = z.instanceof(DraftNewsVideoResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.nullable(z.string()).optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DraftNewsVideoResponseBody$ {
  /** @deprecated use `DraftNewsVideoResponseBody$inboundSchema` instead. */
  export const inboundSchema = DraftNewsVideoResponseBody$inboundSchema;
  /** @deprecated use `DraftNewsVideoResponseBody$outboundSchema` instead. */
  export const outboundSchema = DraftNewsVideoResponseBody$outboundSchema;
  /** @deprecated use `DraftNewsVideoResponseBody$Outbound` instead. */
  export type Outbound = DraftNewsVideoResponseBody$Outbound;
}
