/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * An error response object.
 */
export type GetAudioVoicesResponseBodyData = {
  /**
   * Error message describing the reason for failure.
   */
  message?: string | null | undefined;
};

/**
 * An error response object.
 */
export class GetAudioVoicesResponseBody extends Error {
  /** The original data that was passed to this error instance. */
  data$: GetAudioVoicesResponseBodyData;

  constructor(err: GetAudioVoicesResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.name = "GetAudioVoicesResponseBody";
  }
}

/** @internal */
export const GetAudioVoicesResponseBody$inboundSchema: z.ZodType<
  GetAudioVoicesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.nullable(z.string()).optional(),
})
  .transform((v) => {
    return new GetAudioVoicesResponseBody(v);
  });

/** @internal */
export type GetAudioVoicesResponseBody$Outbound = {
  message?: string | null | undefined;
};

/** @internal */
export const GetAudioVoicesResponseBody$outboundSchema: z.ZodType<
  GetAudioVoicesResponseBody$Outbound,
  z.ZodTypeDef,
  GetAudioVoicesResponseBody
> = z.instanceof(GetAudioVoicesResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.nullable(z.string()).optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAudioVoicesResponseBody$ {
  /** @deprecated use `GetAudioVoicesResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetAudioVoicesResponseBody$inboundSchema;
  /** @deprecated use `GetAudioVoicesResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetAudioVoicesResponseBody$outboundSchema;
  /** @deprecated use `GetAudioVoicesResponseBody$Outbound` instead. */
  export type Outbound = GetAudioVoicesResponseBody$Outbound;
}
