/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * An error response object.
 */
export type GetAudioIdResponseBodyData = {
  /**
   * Error message describing the reason for failure.
   */
  message?: string | null | undefined;
};

/**
 * An error response object.
 */
export class GetAudioIdResponseBody extends Error {
  /** The original data that was passed to this error instance. */
  data$: GetAudioIdResponseBodyData;

  constructor(err: GetAudioIdResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.name = "GetAudioIdResponseBody";
  }
}

/** @internal */
export const GetAudioIdResponseBody$inboundSchema: z.ZodType<
  GetAudioIdResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.nullable(z.string()).optional(),
})
  .transform((v) => {
    return new GetAudioIdResponseBody(v);
  });

/** @internal */
export type GetAudioIdResponseBody$Outbound = {
  message?: string | null | undefined;
};

/** @internal */
export const GetAudioIdResponseBody$outboundSchema: z.ZodType<
  GetAudioIdResponseBody$Outbound,
  z.ZodTypeDef,
  GetAudioIdResponseBody
> = z.instanceof(GetAudioIdResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.nullable(z.string()).optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAudioIdResponseBody$ {
  /** @deprecated use `GetAudioIdResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetAudioIdResponseBody$inboundSchema;
  /** @deprecated use `GetAudioIdResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetAudioIdResponseBody$outboundSchema;
  /** @deprecated use `GetAudioIdResponseBody$Outbound` instead. */
  export type Outbound = GetAudioIdResponseBody$Outbound;
}
