/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ShortGeniusError } from "./shortgeniuserror.js";

/**
 * An error response object.
 */
export type GetAudioResponseBodyData = {
  /**
   * Error message describing the reason for failure.
   */
  message?: string | null | undefined;
};

/**
 * An error response object.
 */
export class GetAudioResponseBody extends ShortGeniusError {
  /** The original data that was passed to this error instance. */
  data$: GetAudioResponseBodyData;

  constructor(
    err: GetAudioResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "GetAudioResponseBody";
  }
}

/** @internal */
export const GetAudioResponseBody$inboundSchema: z.ZodType<
  GetAudioResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.nullable(z.string()).optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetAudioResponseBody(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type GetAudioResponseBody$Outbound = {
  message?: string | null | undefined;
};

/** @internal */
export const GetAudioResponseBody$outboundSchema: z.ZodType<
  GetAudioResponseBody$Outbound,
  z.ZodTypeDef,
  GetAudioResponseBody
> = z.instanceof(GetAudioResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.nullable(z.string()).optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAudioResponseBody$ {
  /** @deprecated use `GetAudioResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetAudioResponseBody$inboundSchema;
  /** @deprecated use `GetAudioResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetAudioResponseBody$outboundSchema;
  /** @deprecated use `GetAudioResponseBody$Outbound` instead. */
  export type Outbound = GetAudioResponseBody$Outbound;
}
