/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * An error response object.
 */
export type GetAllSeriesResponseBodyData = {
  /**
   * Error message describing the reason for failure.
   */
  message?: string | null | undefined;
};

/**
 * An error response object.
 */
export class GetAllSeriesResponseBody extends Error {
  /** The original data that was passed to this error instance. */
  data$: GetAllSeriesResponseBodyData;

  constructor(err: GetAllSeriesResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.name = "GetAllSeriesResponseBody";
  }
}

/** @internal */
export const GetAllSeriesResponseBody$inboundSchema: z.ZodType<
  GetAllSeriesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.nullable(z.string()).optional(),
})
  .transform((v) => {
    return new GetAllSeriesResponseBody(v);
  });

/** @internal */
export type GetAllSeriesResponseBody$Outbound = {
  message?: string | null | undefined;
};

/** @internal */
export const GetAllSeriesResponseBody$outboundSchema: z.ZodType<
  GetAllSeriesResponseBody$Outbound,
  z.ZodTypeDef,
  GetAllSeriesResponseBody
> = z.instanceof(GetAllSeriesResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.nullable(z.string()).optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAllSeriesResponseBody$ {
  /** @deprecated use `GetAllSeriesResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetAllSeriesResponseBody$inboundSchema;
  /** @deprecated use `GetAllSeriesResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetAllSeriesResponseBody$outboundSchema;
  /** @deprecated use `GetAllSeriesResponseBody$Outbound` instead. */
  export type Outbound = GetAllSeriesResponseBody$Outbound;
}
