/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ShortGeniusError } from "./shortgeniuserror.js";

/**
 * An error response object.
 */
export type GetImagesResponseBodyData = {
  /**
   * Error message describing the reason for failure.
   */
  message?: string | null | undefined;
};

/**
 * An error response object.
 */
export class GetImagesResponseBody extends ShortGeniusError {
  /** The original data that was passed to this error instance. */
  data$: GetImagesResponseBodyData;

  constructor(
    err: GetImagesResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "GetImagesResponseBody";
  }
}

/** @internal */
export const GetImagesResponseBody$inboundSchema: z.ZodType<
  GetImagesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.nullable(z.string()).optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetImagesResponseBody(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type GetImagesResponseBody$Outbound = {
  message?: string | null | undefined;
};

/** @internal */
export const GetImagesResponseBody$outboundSchema: z.ZodType<
  GetImagesResponseBody$Outbound,
  z.ZodTypeDef,
  GetImagesResponseBody
> = z.instanceof(GetImagesResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.nullable(z.string()).optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetImagesResponseBody$ {
  /** @deprecated use `GetImagesResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetImagesResponseBody$inboundSchema;
  /** @deprecated use `GetImagesResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetImagesResponseBody$outboundSchema;
  /** @deprecated use `GetImagesResponseBody$Outbound` instead. */
  export type Outbound = GetImagesResponseBody$Outbound;
}
