/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * An error response object.
 */
export type GetImagesIdResponseBodyData = {
  /**
   * Error message describing the reason for failure.
   */
  message?: string | null | undefined;
};

/**
 * An error response object.
 */
export class GetImagesIdResponseBody extends Error {
  /** The original data that was passed to this error instance. */
  data$: GetImagesIdResponseBodyData;

  constructor(err: GetImagesIdResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.name = "GetImagesIdResponseBody";
  }
}

/** @internal */
export const GetImagesIdResponseBody$inboundSchema: z.ZodType<
  GetImagesIdResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.nullable(z.string()).optional(),
})
  .transform((v) => {
    return new GetImagesIdResponseBody(v);
  });

/** @internal */
export type GetImagesIdResponseBody$Outbound = {
  message?: string | null | undefined;
};

/** @internal */
export const GetImagesIdResponseBody$outboundSchema: z.ZodType<
  GetImagesIdResponseBody$Outbound,
  z.ZodTypeDef,
  GetImagesIdResponseBody
> = z.instanceof(GetImagesIdResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.nullable(z.string()).optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetImagesIdResponseBody$ {
  /** @deprecated use `GetImagesIdResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetImagesIdResponseBody$inboundSchema;
  /** @deprecated use `GetImagesIdResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetImagesIdResponseBody$outboundSchema;
  /** @deprecated use `GetImagesIdResponseBody$Outbound` instead. */
  export type Outbound = GetImagesIdResponseBody$Outbound;
}
