/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ShortGeniusError } from "./shortgeniuserror.js";

/**
 * An error response object.
 */
export type GetImageStylesResponseBodyData = {
  /**
   * Error message describing the reason for failure.
   */
  message?: string | null | undefined;
};

/**
 * An error response object.
 */
export class GetImageStylesResponseBody extends ShortGeniusError {
  /** The original data that was passed to this error instance. */
  data$: GetImageStylesResponseBodyData;

  constructor(
    err: GetImageStylesResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "GetImageStylesResponseBody";
  }
}

/** @internal */
export const GetImageStylesResponseBody$inboundSchema: z.ZodType<
  GetImageStylesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.nullable(z.string()).optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetImageStylesResponseBody(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type GetImageStylesResponseBody$Outbound = {
  message?: string | null | undefined;
};

/** @internal */
export const GetImageStylesResponseBody$outboundSchema: z.ZodType<
  GetImageStylesResponseBody$Outbound,
  z.ZodTypeDef,
  GetImageStylesResponseBody
> = z.instanceof(GetImageStylesResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.nullable(z.string()).optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetImageStylesResponseBody$ {
  /** @deprecated use `GetImageStylesResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetImageStylesResponseBody$inboundSchema;
  /** @deprecated use `GetImageStylesResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetImageStylesResponseBody$outboundSchema;
  /** @deprecated use `GetImageStylesResponseBody$Outbound` instead. */
  export type Outbound = GetImageStylesResponseBody$Outbound;
}
