/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * An error response object.
 */
export type GetImagesStylesResponseBodyData = {
  /**
   * Error message describing the reason for failure.
   */
  message?: string | null | undefined;
};

/**
 * An error response object.
 */
export class GetImagesStylesResponseBody extends Error {
  /** The original data that was passed to this error instance. */
  data$: GetImagesStylesResponseBodyData;

  constructor(err: GetImagesStylesResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.name = "GetImagesStylesResponseBody";
  }
}

/** @internal */
export const GetImagesStylesResponseBody$inboundSchema: z.ZodType<
  GetImagesStylesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.nullable(z.string()).optional(),
})
  .transform((v) => {
    return new GetImagesStylesResponseBody(v);
  });

/** @internal */
export type GetImagesStylesResponseBody$Outbound = {
  message?: string | null | undefined;
};

/** @internal */
export const GetImagesStylesResponseBody$outboundSchema: z.ZodType<
  GetImagesStylesResponseBody$Outbound,
  z.ZodTypeDef,
  GetImagesStylesResponseBody
> = z.instanceof(GetImagesStylesResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.nullable(z.string()).optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetImagesStylesResponseBody$ {
  /** @deprecated use `GetImagesStylesResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetImagesStylesResponseBody$inboundSchema;
  /** @deprecated use `GetImagesStylesResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetImagesStylesResponseBody$outboundSchema;
  /** @deprecated use `GetImagesStylesResponseBody$Outbound` instead. */
  export type Outbound = GetImagesStylesResponseBody$Outbound;
}
