/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ShortGeniusError } from "./shortgeniuserror.js";

/**
 * An error response object.
 */
export type GetVideosResponseBodyData = {
  /**
   * Error message describing the reason for failure.
   */
  message?: string | null | undefined;
};

/**
 * An error response object.
 */
export class GetVideosResponseBody extends ShortGeniusError {
  /** The original data that was passed to this error instance. */
  data$: GetVideosResponseBodyData;

  constructor(
    err: GetVideosResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "GetVideosResponseBody";
  }
}

/** @internal */
export const GetVideosResponseBody$inboundSchema: z.ZodType<
  GetVideosResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.nullable(z.string()).optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetVideosResponseBody(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type GetVideosResponseBody$Outbound = {
  message?: string | null | undefined;
};

/** @internal */
export const GetVideosResponseBody$outboundSchema: z.ZodType<
  GetVideosResponseBody$Outbound,
  z.ZodTypeDef,
  GetVideosResponseBody
> = z.instanceof(GetVideosResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.nullable(z.string()).optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetVideosResponseBody$ {
  /** @deprecated use `GetVideosResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetVideosResponseBody$inboundSchema;
  /** @deprecated use `GetVideosResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetVideosResponseBody$outboundSchema;
  /** @deprecated use `GetVideosResponseBody$Outbound` instead. */
  export type Outbound = GetVideosResponseBody$Outbound;
}
