/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * An error response object.
 */
export type GetVideoResponseBodyData = {
  /**
   * Error message describing the reason for failure.
   */
  message?: string | null | undefined;
};

/**
 * An error response object.
 */
export class GetVideoResponseBody extends Error {
  /** The original data that was passed to this error instance. */
  data$: GetVideoResponseBodyData;

  constructor(err: GetVideoResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.name = "GetVideoResponseBody";
  }
}

/** @internal */
export const GetVideoResponseBody$inboundSchema: z.ZodType<
  GetVideoResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.nullable(z.string()).optional(),
})
  .transform((v) => {
    return new GetVideoResponseBody(v);
  });

/** @internal */
export type GetVideoResponseBody$Outbound = {
  message?: string | null | undefined;
};

/** @internal */
export const GetVideoResponseBody$outboundSchema: z.ZodType<
  GetVideoResponseBody$Outbound,
  z.ZodTypeDef,
  GetVideoResponseBody
> = z.instanceof(GetVideoResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.nullable(z.string()).optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetVideoResponseBody$ {
  /** @deprecated use `GetVideoResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetVideoResponseBody$inboundSchema;
  /** @deprecated use `GetVideoResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetVideoResponseBody$outboundSchema;
  /** @deprecated use `GetVideoResponseBody$Outbound` instead. */
  export type Outbound = GetVideoResponseBody$Outbound;
}
