/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * An error response object.
 */
export type PostVideosDraftsQuizVideosResponseBodyData = {
  /**
   * Error message describing the reason for failure.
   */
  message?: string | null | undefined;
};

/**
 * An error response object.
 */
export class PostVideosDraftsQuizVideosResponseBody extends Error {
  /** The original data that was passed to this error instance. */
  data$: PostVideosDraftsQuizVideosResponseBodyData;

  constructor(err: PostVideosDraftsQuizVideosResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.name = "PostVideosDraftsQuizVideosResponseBody";
  }
}

/**
 * An error response object.
 */
export type PostVideosDraftsQuizResponseBodyData = {
  /**
   * Error message describing the reason for failure.
   */
  message?: string | null | undefined;
};

/**
 * An error response object.
 */
export class PostVideosDraftsQuizResponseBody extends Error {
  /** The original data that was passed to this error instance. */
  data$: PostVideosDraftsQuizResponseBodyData;

  constructor(err: PostVideosDraftsQuizResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.name = "PostVideosDraftsQuizResponseBody";
  }
}

/** @internal */
export const PostVideosDraftsQuizVideosResponseBody$inboundSchema: z.ZodType<
  PostVideosDraftsQuizVideosResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.nullable(z.string()).optional(),
})
  .transform((v) => {
    return new PostVideosDraftsQuizVideosResponseBody(v);
  });

/** @internal */
export type PostVideosDraftsQuizVideosResponseBody$Outbound = {
  message?: string | null | undefined;
};

/** @internal */
export const PostVideosDraftsQuizVideosResponseBody$outboundSchema: z.ZodType<
  PostVideosDraftsQuizVideosResponseBody$Outbound,
  z.ZodTypeDef,
  PostVideosDraftsQuizVideosResponseBody
> = z.instanceof(PostVideosDraftsQuizVideosResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.nullable(z.string()).optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostVideosDraftsQuizVideosResponseBody$ {
  /** @deprecated use `PostVideosDraftsQuizVideosResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    PostVideosDraftsQuizVideosResponseBody$inboundSchema;
  /** @deprecated use `PostVideosDraftsQuizVideosResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    PostVideosDraftsQuizVideosResponseBody$outboundSchema;
  /** @deprecated use `PostVideosDraftsQuizVideosResponseBody$Outbound` instead. */
  export type Outbound = PostVideosDraftsQuizVideosResponseBody$Outbound;
}

/** @internal */
export const PostVideosDraftsQuizResponseBody$inboundSchema: z.ZodType<
  PostVideosDraftsQuizResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.nullable(z.string()).optional(),
})
  .transform((v) => {
    return new PostVideosDraftsQuizResponseBody(v);
  });

/** @internal */
export type PostVideosDraftsQuizResponseBody$Outbound = {
  message?: string | null | undefined;
};

/** @internal */
export const PostVideosDraftsQuizResponseBody$outboundSchema: z.ZodType<
  PostVideosDraftsQuizResponseBody$Outbound,
  z.ZodTypeDef,
  PostVideosDraftsQuizResponseBody
> = z.instanceof(PostVideosDraftsQuizResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.nullable(z.string()).optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostVideosDraftsQuizResponseBody$ {
  /** @deprecated use `PostVideosDraftsQuizResponseBody$inboundSchema` instead. */
  export const inboundSchema = PostVideosDraftsQuizResponseBody$inboundSchema;
  /** @deprecated use `PostVideosDraftsQuizResponseBody$outboundSchema` instead. */
  export const outboundSchema = PostVideosDraftsQuizResponseBody$outboundSchema;
  /** @deprecated use `PostVideosDraftsQuizResponseBody$Outbound` instead. */
  export type Outbound = PostVideosDraftsQuizResponseBody$Outbound;
}
