/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * An error response object.
 */
export type PostVideosDraftsVideosResponseBodyData = {
  /**
   * Error message describing the reason for failure.
   */
  message?: string | null | undefined;
};

/**
 * An error response object.
 */
export class PostVideosDraftsVideosResponseBody extends Error {
  /** The original data that was passed to this error instance. */
  data$: PostVideosDraftsVideosResponseBodyData;

  constructor(err: PostVideosDraftsVideosResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.name = "PostVideosDraftsVideosResponseBody";
  }
}

/**
 * An error response object.
 */
export type PostVideosDraftsResponseBodyData = {
  /**
   * Error message describing the reason for failure.
   */
  message?: string | null | undefined;
};

/**
 * An error response object.
 */
export class PostVideosDraftsResponseBody extends Error {
  /** The original data that was passed to this error instance. */
  data$: PostVideosDraftsResponseBodyData;

  constructor(err: PostVideosDraftsResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.name = "PostVideosDraftsResponseBody";
  }
}

/** @internal */
export const PostVideosDraftsVideosResponseBody$inboundSchema: z.ZodType<
  PostVideosDraftsVideosResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.nullable(z.string()).optional(),
})
  .transform((v) => {
    return new PostVideosDraftsVideosResponseBody(v);
  });

/** @internal */
export type PostVideosDraftsVideosResponseBody$Outbound = {
  message?: string | null | undefined;
};

/** @internal */
export const PostVideosDraftsVideosResponseBody$outboundSchema: z.ZodType<
  PostVideosDraftsVideosResponseBody$Outbound,
  z.ZodTypeDef,
  PostVideosDraftsVideosResponseBody
> = z.instanceof(PostVideosDraftsVideosResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.nullable(z.string()).optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostVideosDraftsVideosResponseBody$ {
  /** @deprecated use `PostVideosDraftsVideosResponseBody$inboundSchema` instead. */
  export const inboundSchema = PostVideosDraftsVideosResponseBody$inboundSchema;
  /** @deprecated use `PostVideosDraftsVideosResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    PostVideosDraftsVideosResponseBody$outboundSchema;
  /** @deprecated use `PostVideosDraftsVideosResponseBody$Outbound` instead. */
  export type Outbound = PostVideosDraftsVideosResponseBody$Outbound;
}

/** @internal */
export const PostVideosDraftsResponseBody$inboundSchema: z.ZodType<
  PostVideosDraftsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.nullable(z.string()).optional(),
})
  .transform((v) => {
    return new PostVideosDraftsResponseBody(v);
  });

/** @internal */
export type PostVideosDraftsResponseBody$Outbound = {
  message?: string | null | undefined;
};

/** @internal */
export const PostVideosDraftsResponseBody$outboundSchema: z.ZodType<
  PostVideosDraftsResponseBody$Outbound,
  z.ZodTypeDef,
  PostVideosDraftsResponseBody
> = z.instanceof(PostVideosDraftsResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.nullable(z.string()).optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostVideosDraftsResponseBody$ {
  /** @deprecated use `PostVideosDraftsResponseBody$inboundSchema` instead. */
  export const inboundSchema = PostVideosDraftsResponseBody$inboundSchema;
  /** @deprecated use `PostVideosDraftsResponseBody$outboundSchema` instead. */
  export const outboundSchema = PostVideosDraftsResponseBody$outboundSchema;
  /** @deprecated use `PostVideosDraftsResponseBody$Outbound` instead. */
  export type Outbound = PostVideosDraftsResponseBody$Outbound;
}
