/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * An error response object.
 */
export type PostVideosTopicsVideosResponseBodyData = {
  /**
   * Error message describing the reason for failure.
   */
  message?: string | null | undefined;
};

/**
 * An error response object.
 */
export class PostVideosTopicsVideosResponseBody extends Error {
  /** The original data that was passed to this error instance. */
  data$: PostVideosTopicsVideosResponseBodyData;

  constructor(err: PostVideosTopicsVideosResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.name = "PostVideosTopicsVideosResponseBody";
  }
}

/**
 * An error response object.
 */
export type PostVideosTopicsResponseBodyData = {
  /**
   * Error message describing the reason for failure.
   */
  message?: string | null | undefined;
};

/**
 * An error response object.
 */
export class PostVideosTopicsResponseBody extends Error {
  /** The original data that was passed to this error instance. */
  data$: PostVideosTopicsResponseBodyData;

  constructor(err: PostVideosTopicsResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.name = "PostVideosTopicsResponseBody";
  }
}

/** @internal */
export const PostVideosTopicsVideosResponseBody$inboundSchema: z.ZodType<
  PostVideosTopicsVideosResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.nullable(z.string()).optional(),
})
  .transform((v) => {
    return new PostVideosTopicsVideosResponseBody(v);
  });

/** @internal */
export type PostVideosTopicsVideosResponseBody$Outbound = {
  message?: string | null | undefined;
};

/** @internal */
export const PostVideosTopicsVideosResponseBody$outboundSchema: z.ZodType<
  PostVideosTopicsVideosResponseBody$Outbound,
  z.ZodTypeDef,
  PostVideosTopicsVideosResponseBody
> = z.instanceof(PostVideosTopicsVideosResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.nullable(z.string()).optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostVideosTopicsVideosResponseBody$ {
  /** @deprecated use `PostVideosTopicsVideosResponseBody$inboundSchema` instead. */
  export const inboundSchema = PostVideosTopicsVideosResponseBody$inboundSchema;
  /** @deprecated use `PostVideosTopicsVideosResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    PostVideosTopicsVideosResponseBody$outboundSchema;
  /** @deprecated use `PostVideosTopicsVideosResponseBody$Outbound` instead. */
  export type Outbound = PostVideosTopicsVideosResponseBody$Outbound;
}

/** @internal */
export const PostVideosTopicsResponseBody$inboundSchema: z.ZodType<
  PostVideosTopicsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.nullable(z.string()).optional(),
})
  .transform((v) => {
    return new PostVideosTopicsResponseBody(v);
  });

/** @internal */
export type PostVideosTopicsResponseBody$Outbound = {
  message?: string | null | undefined;
};

/** @internal */
export const PostVideosTopicsResponseBody$outboundSchema: z.ZodType<
  PostVideosTopicsResponseBody$Outbound,
  z.ZodTypeDef,
  PostVideosTopicsResponseBody
> = z.instanceof(PostVideosTopicsResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.nullable(z.string()).optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostVideosTopicsResponseBody$ {
  /** @deprecated use `PostVideosTopicsResponseBody$inboundSchema` instead. */
  export const inboundSchema = PostVideosTopicsResponseBody$inboundSchema;
  /** @deprecated use `PostVideosTopicsResponseBody$outboundSchema` instead. */
  export const outboundSchema = PostVideosTopicsResponseBody$outboundSchema;
  /** @deprecated use `PostVideosTopicsResponseBody$Outbound` instead. */
  export type Outbound = PostVideosTopicsResponseBody$Outbound;
}
