/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { audioGetAudioId } from "../../funcs/audioGetAudioId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetAudioIdRequest$inboundSchema,
};

export const tool$audioGetAudioId: ToolDefinition<typeof args> = {
  name: "audio_get-audio-id",
  description: `Get audio`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await audioGetAudioId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
