/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { audioGetAudioVoices } from "../../funcs/audioGetAudioVoices.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetAudioVoicesRequest$inboundSchema,
};

export const tool$audioGetAudioVoices: ToolDefinition<typeof args> = {
  name: "audio_get-audio-voices",
  description: `List voices

Gets a list of all voices available for text-to-speech.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await audioGetAudioVoices(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
