/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { audioGetAudioVoicesId } from "../../funcs/audioGetAudioVoicesId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetAudioVoicesIdRequest$inboundSchema,
};

export const tool$audioGetAudioVoicesId: ToolDefinition<typeof args> = {
  name: "audio_get-audio-voices-id",
  description: `Get voice`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await audioGetAudioVoicesId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
