/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { getImageStyles } from "../../funcs/getImageStyles.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$getImageStyles: ToolDefinition = {
  name: "get-image-styles",
  description: `List image styles

Get all the image styles available for creating images.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await getImageStyles(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
