/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { getImage } from "../../funcs/getImage.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetImageRequest$inboundSchema,
};

export const tool$getImage: ToolDefinition<typeof args> = {
  name: "get-image",
  description: `Get image`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await getImage(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
