/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { getMusicGenres } from "../../funcs/getMusicGenres.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$getMusicGenres: ToolDefinition = {
  name: "get-music-genres",
  description: `List music genres

Gets a list of all music genres available.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await getMusicGenres(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
