/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { getMusic } from "../../funcs/getMusic.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  id: z.string(),
};

export const tool$getMusic: ToolDefinition<typeof args> = {
  name: "get-music",
  description: `List music

Gets a list of all music tracks available for the specified genre.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await getMusic(
      client,
      args.id,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
