/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { getUsage } from "../../funcs/getUsage.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$getUsage: ToolDefinition = {
  name: "get-usage",
  description: `Get usage

Get usage information.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await getUsage(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
