/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { imagesGetImages } from "../../funcs/imagesGetImages.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetImagesRequest$inboundSchema,
};

export const tool$imagesGetImages: ToolDefinition<typeof args> = {
  name: "images_get-images",
  description: `List images

Get all the images you have generated.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await imagesGetImages(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
