/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { imagesGetImagesId } from "../../funcs/imagesGetImagesId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetImagesIdRequest$inboundSchema,
};

export const tool$imagesGetImagesId: ToolDefinition<typeof args> = {
  name: "images_get-images-id",
  description: `Get image`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await imagesGetImagesId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
