/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { musicGetMusicGenresId } from "../../funcs/musicGetMusicGenresId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetMusicGenresIdRequest$inboundSchema,
};

export const tool$musicGetMusicGenresId: ToolDefinition<typeof args> = {
  name: "music_get-music-genres-id",
  description: `List music

Gets a list of all music tracks available for the specified genre.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await musicGetMusicGenresId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
