/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { publishingGetConnections } from "../../funcs/publishingGetConnections.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$publishingGetConnections: ToolDefinition = {
  name: "publishing_get-connections",
  description: `Get connections

Get all the video publishing destinations you have configured.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await publishingGetConnections(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
