/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { seriesGetSeriesId } from "../../funcs/seriesGetSeriesId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetSeriesIdRequest$inboundSchema,
};

export const tool$seriesGetSeriesId: ToolDefinition<typeof args> = {
  name: "series_get-series-id",
  description: `Get series`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await seriesGetSeriesId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
