/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { statusCheck } from "../../funcs/statusCheck.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$statusCheck: ToolDefinition = {
  name: "status-check",
  description: `Health check

Check if the service is running.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await statusCheck(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
