/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { videosPostVideosDraftsNews } from "../../funcs/videosPostVideosDraftsNews.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostVideosDraftsNewsRequestBody$inboundSchema.optional(),
};

export const tool$videosPostVideosDraftsNews: ToolDefinition<typeof args> = {
  name: "videos_post-videos-drafts-news",
  description: `Draft news video

Retrieve the latest news on the provided topic, then generate video scenes. After calling this endpoint, call [Create Video](#tag/videos/POST/videos) with the results to create the video.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await videosPostVideosDraftsNews(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
