/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { ShortGeniusCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import { createRegisterTool } from "./tools.js";
import { tool$createImage } from "./tools/createImage.js";
import { tool$createSeries } from "./tools/createSeries.js";
import { tool$createSpeech } from "./tools/createSpeech.js";
import { tool$createVideo } from "./tools/createVideo.js";
import { tool$draftNewsVideo } from "./tools/draftNewsVideo.js";
import { tool$draftQuizVideo } from "./tools/draftQuizVideo.js";
import { tool$draftVideo } from "./tools/draftVideo.js";
import { tool$draftVideoFromScript } from "./tools/draftVideoFromScript.js";
import { tool$draftVideoFromURL } from "./tools/draftVideoFromURL.js";
import { tool$generateVideoTopics } from "./tools/generateVideoTopics.js";
import { tool$getAllAudio } from "./tools/getAllAudio.js";
import { tool$getAllSeries } from "./tools/getAllSeries.js";
import { tool$getAudio } from "./tools/getAudio.js";
import { tool$getConnections } from "./tools/getConnections.js";
import { tool$getImage } from "./tools/getImage.js";
import { tool$getImages } from "./tools/getImages.js";
import { tool$getImageStyles } from "./tools/getImageStyles.js";
import { tool$getMusic } from "./tools/getMusic.js";
import { tool$getMusicGenres } from "./tools/getMusicGenres.js";
import { tool$getSeries } from "./tools/getSeries.js";
import { tool$getUsage } from "./tools/getUsage.js";
import { tool$getVideo } from "./tools/getVideo.js";
import { tool$getVideos } from "./tools/getVideos.js";
import { tool$getVoice } from "./tools/getVoice.js";
import { tool$getVoices } from "./tools/getVoices.js";
import { tool$statusCheck } from "./tools/statusCheck.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  scopes?: MCPScope[] | undefined;
  serverURL?: string | undefined;
  bearerAuth?: SDKOptions["bearerAuth"] | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
}) {
  const server = new McpServer({
    name: "ShortGenius",
    version: "0.5.0",
  });

  const client = new ShortGeniusCore({
    bearerAuth: deps.bearerAuth,
    serverURL: deps.serverURL,
    serverIdx: deps.serverIdx,
  });

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const tool = createRegisterTool(
    deps.logger,
    server,
    client,
    scopes,
    allowedTools,
  );
  const resource = createRegisterResource(deps.logger, server, client, scopes);
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    client,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, client, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$getMusicGenres);
  tool(tool$getMusic);
  tool(tool$draftVideo);
  tool(tool$draftVideoFromURL);
  tool(tool$draftVideoFromScript);
  tool(tool$draftQuizVideo);
  tool(tool$draftNewsVideo);
  tool(tool$getVideo);
  tool(tool$getVideos);
  tool(tool$createVideo);
  tool(tool$generateVideoTopics);
  tool(tool$createSeries);
  tool(tool$getAllSeries);
  tool(tool$getSeries);
  tool(tool$getConnections);
  tool(tool$createImage);
  tool(tool$getImages);
  tool(tool$getImage);
  tool(tool$getImageStyles);
  tool(tool$createSpeech);
  tool(tool$getAllAudio);
  tool(tool$getAudio);
  tool(tool$getVoices);
  tool(tool$getVoice);
  tool(tool$getUsage);
  tool(tool$statusCheck);

  return server;
}
