/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { publishingGetConnections } from "../funcs/publishingGetConnections.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Publishing extends ClientSDK {
  /**
   * Get connections
   *
   * @remarks
   * Get all the video publishing destinations you have configured.
   */
  async getConnections(
    options?: RequestOptions,
  ): Promise<Array<components.Connection>> {
    return unwrapAsync(publishingGetConnections(
      this,
      options,
    ));
  }
}
