/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { seriesGetSeries } from "../funcs/seriesGetSeries.js";
import { seriesGetSeriesId } from "../funcs/seriesGetSeriesId.js";
import { seriesPostSeries } from "../funcs/seriesPostSeries.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Series extends ClientSDK {
  /**
   * Create series
   */
  async postSeries(
    request?: operations.PostSeriesRequestBody | undefined,
    options?: RequestOptions,
  ): Promise<components.Series> {
    return unwrapAsync(seriesPostSeries(
      this,
      request,
      options,
    ));
  }

  /**
   * List series
   */
  async getSeries(
    request: operations.GetSeriesRequest,
    options?: RequestOptions,
  ): Promise<operations.GetSeriesResponseBody> {
    return unwrapAsync(seriesGetSeries(
      this,
      request,
      options,
    ));
  }

  /**
   * Get series
   */
  async getSeriesId(
    request: operations.GetSeriesIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetSeriesIdResponseBody> {
    return unwrapAsync(seriesGetSeriesId(
      this,
      request,
      options,
    ));
  }
}
