workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    ShortGenius API:
        inputs:
            - location: https://shortgenius.com/openapi.yaml
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/shortgenius/production/short-genius-api
targets:
    shortgenius:
        target: typescript
        source: ShortGenius API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/shortgenius/production/short-genius-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
