/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Indicates if the server is healthy.
 */
export const Status = {
  Ok: "ok",
} as const;
/**
 * Indicates if the server is healthy.
 */
export type Status = ClosedEnum<typeof Status>;

/**
 * Health status response.
 */
export type CheckHealthResponseBody = {
  /**
   * Indicates if the server is healthy.
   */
  status: Status;
};

/** @internal */
export const Status$inboundSchema: z.ZodNativeEnum<typeof Status> = z
  .nativeEnum(Status);

/** @internal */
export const Status$outboundSchema: z.ZodNativeEnum<typeof Status> =
  Status$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Status$ {
  /** @deprecated use `Status$inboundSchema` instead. */
  export const inboundSchema = Status$inboundSchema;
  /** @deprecated use `Status$outboundSchema` instead. */
  export const outboundSchema = Status$outboundSchema;
}

/** @internal */
export const CheckHealthResponseBody$inboundSchema: z.ZodType<
  CheckHealthResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: Status$inboundSchema,
});

/** @internal */
export type CheckHealthResponseBody$Outbound = {
  status: string;
};

/** @internal */
export const CheckHealthResponseBody$outboundSchema: z.ZodType<
  CheckHealthResponseBody$Outbound,
  z.ZodTypeDef,
  CheckHealthResponseBody
> = z.object({
  status: Status$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CheckHealthResponseBody$ {
  /** @deprecated use `CheckHealthResponseBody$inboundSchema` instead. */
  export const inboundSchema = CheckHealthResponseBody$inboundSchema;
  /** @deprecated use `CheckHealthResponseBody$outboundSchema` instead. */
  export const outboundSchema = CheckHealthResponseBody$outboundSchema;
  /** @deprecated use `CheckHealthResponseBody$Outbound` instead. */
  export type Outbound = CheckHealthResponseBody$Outbound;
}

export function checkHealthResponseBodyToJSON(
  checkHealthResponseBody: CheckHealthResponseBody,
): string {
  return JSON.stringify(
    CheckHealthResponseBody$outboundSchema.parse(checkHealthResponseBody),
  );
}

export function checkHealthResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CheckHealthResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CheckHealthResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CheckHealthResponseBody' from JSON`,
  );
}
