/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetAudioIdRequest = {
  /**
   * The unique ID of the audio record to retrieve.
   */
  id: string;
};

/** @internal */
export const GetAudioIdRequest$inboundSchema: z.ZodType<
  GetAudioIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type GetAudioIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetAudioIdRequest$outboundSchema: z.ZodType<
  GetAudioIdRequest$Outbound,
  z.ZodTypeDef,
  GetAudioIdRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAudioIdRequest$ {
  /** @deprecated use `GetAudioIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetAudioIdRequest$inboundSchema;
  /** @deprecated use `GetAudioIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetAudioIdRequest$outboundSchema;
  /** @deprecated use `GetAudioIdRequest$Outbound` instead. */
  export type Outbound = GetAudioIdRequest$Outbound;
}

export function getAudioIdRequestToJSON(
  getAudioIdRequest: GetAudioIdRequest,
): string {
  return JSON.stringify(
    GetAudioIdRequest$outboundSchema.parse(getAudioIdRequest),
  );
}

export function getAudioIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetAudioIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAudioIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAudioIdRequest' from JSON`,
  );
}
