/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetSeriesRequest = {
  /**
   * The page number to retrieve.
   */
  page?: number | undefined;
  /**
   * The maximum number of items per page.
   */
  limit?: number | undefined;
};

/**
 * Response for listing video series.
 */
export type GetSeriesResponseBody = {
  /**
   * Array of video series.
   */
  series: Array<components.Series>;
  /**
   * Indicates if more items are available.
   */
  hasMore: boolean;
};

/** @internal */
export const GetSeriesRequest$inboundSchema: z.ZodType<
  GetSeriesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  page: z.number().default(0),
  limit: z.number().default(50),
});

/** @internal */
export type GetSeriesRequest$Outbound = {
  page: number;
  limit: number;
};

/** @internal */
export const GetSeriesRequest$outboundSchema: z.ZodType<
  GetSeriesRequest$Outbound,
  z.ZodTypeDef,
  GetSeriesRequest
> = z.object({
  page: z.number().default(0),
  limit: z.number().default(50),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetSeriesRequest$ {
  /** @deprecated use `GetSeriesRequest$inboundSchema` instead. */
  export const inboundSchema = GetSeriesRequest$inboundSchema;
  /** @deprecated use `GetSeriesRequest$outboundSchema` instead. */
  export const outboundSchema = GetSeriesRequest$outboundSchema;
  /** @deprecated use `GetSeriesRequest$Outbound` instead. */
  export type Outbound = GetSeriesRequest$Outbound;
}

export function getSeriesRequestToJSON(
  getSeriesRequest: GetSeriesRequest,
): string {
  return JSON.stringify(
    GetSeriesRequest$outboundSchema.parse(getSeriesRequest),
  );
}

export function getSeriesRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetSeriesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSeriesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSeriesRequest' from JSON`,
  );
}

/** @internal */
export const GetSeriesResponseBody$inboundSchema: z.ZodType<
  GetSeriesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  series: z.array(components.Series$inboundSchema),
  has_more: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    "has_more": "hasMore",
  });
});

/** @internal */
export type GetSeriesResponseBody$Outbound = {
  series: Array<components.Series$Outbound>;
  has_more: boolean;
};

/** @internal */
export const GetSeriesResponseBody$outboundSchema: z.ZodType<
  GetSeriesResponseBody$Outbound,
  z.ZodTypeDef,
  GetSeriesResponseBody
> = z.object({
  series: z.array(components.Series$outboundSchema),
  hasMore: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    hasMore: "has_more",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetSeriesResponseBody$ {
  /** @deprecated use `GetSeriesResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetSeriesResponseBody$inboundSchema;
  /** @deprecated use `GetSeriesResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetSeriesResponseBody$outboundSchema;
  /** @deprecated use `GetSeriesResponseBody$Outbound` instead. */
  export type Outbound = GetSeriesResponseBody$Outbound;
}

export function getSeriesResponseBodyToJSON(
  getSeriesResponseBody: GetSeriesResponseBody,
): string {
  return JSON.stringify(
    GetSeriesResponseBody$outboundSchema.parse(getSeriesResponseBody),
  );
}

export function getSeriesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetSeriesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSeriesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSeriesResponseBody' from JSON`,
  );
}
