/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetVoiceRequest = {
  /**
   * The unique ID of the voice to retrieve.
   */
  id: string;
};

/** @internal */
export const GetVoiceRequest$inboundSchema: z.ZodType<
  GetVoiceRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type GetVoiceRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetVoiceRequest$outboundSchema: z.ZodType<
  GetVoiceRequest$Outbound,
  z.ZodTypeDef,
  GetVoiceRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetVoiceRequest$ {
  /** @deprecated use `GetVoiceRequest$inboundSchema` instead. */
  export const inboundSchema = GetVoiceRequest$inboundSchema;
  /** @deprecated use `GetVoiceRequest$outboundSchema` instead. */
  export const outboundSchema = GetVoiceRequest$outboundSchema;
  /** @deprecated use `GetVoiceRequest$Outbound` instead. */
  export type Outbound = GetVoiceRequest$Outbound;
}

export function getVoiceRequestToJSON(
  getVoiceRequest: GetVoiceRequest,
): string {
  return JSON.stringify(GetVoiceRequest$outboundSchema.parse(getVoiceRequest));
}

export function getVoiceRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetVoiceRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetVoiceRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetVoiceRequest' from JSON`,
  );
}
