/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetVideosIdRequest = {
  /**
   * The unique ID of the video to retrieve.
   */
  id: string;
};

/** @internal */
export const GetVideosIdRequest$inboundSchema: z.ZodType<
  GetVideosIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type GetVideosIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetVideosIdRequest$outboundSchema: z.ZodType<
  GetVideosIdRequest$Outbound,
  z.ZodTypeDef,
  GetVideosIdRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetVideosIdRequest$ {
  /** @deprecated use `GetVideosIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetVideosIdRequest$inboundSchema;
  /** @deprecated use `GetVideosIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetVideosIdRequest$outboundSchema;
  /** @deprecated use `GetVideosIdRequest$Outbound` instead. */
  export type Outbound = GetVideosIdRequest$Outbound;
}

export function getVideosIdRequestToJSON(
  getVideosIdRequest: GetVideosIdRequest,
): string {
  return JSON.stringify(
    GetVideosIdRequest$outboundSchema.parse(getVideosIdRequest),
  );
}

export function getVideosIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetVideosIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetVideosIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetVideosIdRequest' from JSON`,
  );
}
