/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The locale of the video.
 */
export const PostVideosDraftsQuizLocale = {
  AfZA: "af-ZA",
  IDID: "id-ID",
  MsMY: "ms-MY",
  CaES: "ca-ES",
  CsCZ: "cs-CZ",
  DaDK: "da-DK",
  DEDE: "de-DE",
  EnUS: "en-US",
  ESES: "es-ES",
  Es419: "es-419",
  FrCA: "fr-CA",
  FRFR: "fr-FR",
  HRHR: "hr-HR",
  ITIT: "it-IT",
  HUHU: "hu-HU",
  NLNL: "nl-NL",
  NONO: "no-NO",
  PLPL: "pl-PL",
  PtBR: "pt-BR",
  PTPT: "pt-PT",
  RORO: "ro-RO",
  SKSK: "sk-SK",
  FIFI: "fi-FI",
  SvSE: "sv-SE",
  ViVN: "vi-VN",
  TRTR: "tr-TR",
  ElGR: "el-GR",
  RURU: "ru-RU",
  SrSP: "sr-SP",
  UkUA: "uk-UA",
  HyAM: "hy-AM",
  HeIL: "he-IL",
  UrPK: "ur-PK",
  ArSA: "ar-SA",
  HiIN: "hi-IN",
  THTH: "th-TH",
  KoKR: "ko-KR",
  JaJP: "ja-JP",
  ZhCN: "zh-CN",
  ZhTW: "zh-TW",
  Auto: "auto",
} as const;
/**
 * The locale of the video.
 */
export type PostVideosDraftsQuizLocale = ClosedEnum<
  typeof PostVideosDraftsQuizLocale
>;

export type PostVideosDraftsQuizRequestBody = {
  /**
   * The topic you would like to make a quiz about.
   */
  topic: string;
  /**
   * The locale of the video.
   */
  locale?: PostVideosDraftsQuizLocale | undefined;
};

/** @internal */
export const PostVideosDraftsQuizLocale$inboundSchema: z.ZodNativeEnum<
  typeof PostVideosDraftsQuizLocale
> = z.nativeEnum(PostVideosDraftsQuizLocale);

/** @internal */
export const PostVideosDraftsQuizLocale$outboundSchema: z.ZodNativeEnum<
  typeof PostVideosDraftsQuizLocale
> = PostVideosDraftsQuizLocale$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostVideosDraftsQuizLocale$ {
  /** @deprecated use `PostVideosDraftsQuizLocale$inboundSchema` instead. */
  export const inboundSchema = PostVideosDraftsQuizLocale$inboundSchema;
  /** @deprecated use `PostVideosDraftsQuizLocale$outboundSchema` instead. */
  export const outboundSchema = PostVideosDraftsQuizLocale$outboundSchema;
}

/** @internal */
export const PostVideosDraftsQuizRequestBody$inboundSchema: z.ZodType<
  PostVideosDraftsQuizRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  topic: z.string(),
  locale: PostVideosDraftsQuizLocale$inboundSchema.default("auto"),
});

/** @internal */
export type PostVideosDraftsQuizRequestBody$Outbound = {
  topic: string;
  locale: string;
};

/** @internal */
export const PostVideosDraftsQuizRequestBody$outboundSchema: z.ZodType<
  PostVideosDraftsQuizRequestBody$Outbound,
  z.ZodTypeDef,
  PostVideosDraftsQuizRequestBody
> = z.object({
  topic: z.string(),
  locale: PostVideosDraftsQuizLocale$outboundSchema.default("auto"),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostVideosDraftsQuizRequestBody$ {
  /** @deprecated use `PostVideosDraftsQuizRequestBody$inboundSchema` instead. */
  export const inboundSchema = PostVideosDraftsQuizRequestBody$inboundSchema;
  /** @deprecated use `PostVideosDraftsQuizRequestBody$outboundSchema` instead. */
  export const outboundSchema = PostVideosDraftsQuizRequestBody$outboundSchema;
  /** @deprecated use `PostVideosDraftsQuizRequestBody$Outbound` instead. */
  export type Outbound = PostVideosDraftsQuizRequestBody$Outbound;
}

export function postVideosDraftsQuizRequestBodyToJSON(
  postVideosDraftsQuizRequestBody: PostVideosDraftsQuizRequestBody,
): string {
  return JSON.stringify(
    PostVideosDraftsQuizRequestBody$outboundSchema.parse(
      postVideosDraftsQuizRequestBody,
    ),
  );
}

export function postVideosDraftsQuizRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostVideosDraftsQuizRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostVideosDraftsQuizRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostVideosDraftsQuizRequestBody' from JSON`,
  );
}
