/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The locale of the video.
 */
export const PostVideosDraftsNewsLocale = {
  AfZA: "af-ZA",
  IDID: "id-ID",
  MsMY: "ms-MY",
  CaES: "ca-ES",
  CsCZ: "cs-CZ",
  DaDK: "da-DK",
  DEDE: "de-DE",
  EnUS: "en-US",
  ESES: "es-ES",
  Es419: "es-419",
  FrCA: "fr-CA",
  FRFR: "fr-FR",
  HRHR: "hr-HR",
  ITIT: "it-IT",
  HUHU: "hu-HU",
  NLNL: "nl-NL",
  NONO: "no-NO",
  PLPL: "pl-PL",
  PtBR: "pt-BR",
  PTPT: "pt-PT",
  RORO: "ro-RO",
  SKSK: "sk-SK",
  FIFI: "fi-FI",
  SvSE: "sv-SE",
  ViVN: "vi-VN",
  TRTR: "tr-TR",
  ElGR: "el-GR",
  RURU: "ru-RU",
  SrSP: "sr-SP",
  UkUA: "uk-UA",
  HyAM: "hy-AM",
  HeIL: "he-IL",
  UrPK: "ur-PK",
  ArSA: "ar-SA",
  HiIN: "hi-IN",
  THTH: "th-TH",
  KoKR: "ko-KR",
  JaJP: "ja-JP",
  ZhCN: "zh-CN",
  ZhTW: "zh-TW",
  Auto: "auto",
} as const;
/**
 * The locale of the video.
 */
export type PostVideosDraftsNewsLocale = ClosedEnum<
  typeof PostVideosDraftsNewsLocale
>;

export type PostVideosDraftsNewsRequestBody = {
  /**
   * The topic you would like the AI to retrieve news about.
   */
  topic: string;
  /**
   * The locale of the video.
   */
  locale?: PostVideosDraftsNewsLocale | undefined;
};

/** @internal */
export const PostVideosDraftsNewsLocale$inboundSchema: z.ZodNativeEnum<
  typeof PostVideosDraftsNewsLocale
> = z.nativeEnum(PostVideosDraftsNewsLocale);

/** @internal */
export const PostVideosDraftsNewsLocale$outboundSchema: z.ZodNativeEnum<
  typeof PostVideosDraftsNewsLocale
> = PostVideosDraftsNewsLocale$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostVideosDraftsNewsLocale$ {
  /** @deprecated use `PostVideosDraftsNewsLocale$inboundSchema` instead. */
  export const inboundSchema = PostVideosDraftsNewsLocale$inboundSchema;
  /** @deprecated use `PostVideosDraftsNewsLocale$outboundSchema` instead. */
  export const outboundSchema = PostVideosDraftsNewsLocale$outboundSchema;
}

/** @internal */
export const PostVideosDraftsNewsRequestBody$inboundSchema: z.ZodType<
  PostVideosDraftsNewsRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  topic: z.string(),
  locale: PostVideosDraftsNewsLocale$inboundSchema.default("auto"),
});

/** @internal */
export type PostVideosDraftsNewsRequestBody$Outbound = {
  topic: string;
  locale: string;
};

/** @internal */
export const PostVideosDraftsNewsRequestBody$outboundSchema: z.ZodType<
  PostVideosDraftsNewsRequestBody$Outbound,
  z.ZodTypeDef,
  PostVideosDraftsNewsRequestBody
> = z.object({
  topic: z.string(),
  locale: PostVideosDraftsNewsLocale$outboundSchema.default("auto"),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostVideosDraftsNewsRequestBody$ {
  /** @deprecated use `PostVideosDraftsNewsRequestBody$inboundSchema` instead. */
  export const inboundSchema = PostVideosDraftsNewsRequestBody$inboundSchema;
  /** @deprecated use `PostVideosDraftsNewsRequestBody$outboundSchema` instead. */
  export const outboundSchema = PostVideosDraftsNewsRequestBody$outboundSchema;
  /** @deprecated use `PostVideosDraftsNewsRequestBody$Outbound` instead. */
  export type Outbound = PostVideosDraftsNewsRequestBody$Outbound;
}

export function postVideosDraftsNewsRequestBodyToJSON(
  postVideosDraftsNewsRequestBody: PostVideosDraftsNewsRequestBody,
): string {
  return JSON.stringify(
    PostVideosDraftsNewsRequestBody$outboundSchema.parse(
      postVideosDraftsNewsRequestBody,
    ),
  );
}

export function postVideosDraftsNewsRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostVideosDraftsNewsRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostVideosDraftsNewsRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostVideosDraftsNewsRequestBody' from JSON`,
  );
}
