/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const PostSeriesContentType = {
  Custom: "Custom",
  News: "News",
  Quiz: "Quiz",
  History: "History",
  Scary: "Scary",
  Motivational: "Motivational",
  Bedtime: "Bedtime",
  FunFacts: "FunFacts",
  LifeTips: "LifeTips",
  Eli5: "ELI5",
  Philosophy: "Philosophy",
} as const;
export type PostSeriesContentType = ClosedEnum<typeof PostSeriesContentType>;

/**
 * Locale for the generated video.
 */
export const PostSeriesLocale = {
  AfZA: "af-ZA",
  IDID: "id-ID",
  MsMY: "ms-MY",
  CaES: "ca-ES",
  CsCZ: "cs-CZ",
  DaDK: "da-DK",
  DEDE: "de-DE",
  EnUS: "en-US",
  ESES: "es-ES",
  Es419: "es-419",
  FrCA: "fr-CA",
  FRFR: "fr-FR",
  HRHR: "hr-HR",
  ITIT: "it-IT",
  HUHU: "hu-HU",
  NLNL: "nl-NL",
  NONO: "no-NO",
  PLPL: "pl-PL",
  PtBR: "pt-BR",
  PTPT: "pt-PT",
  RORO: "ro-RO",
  SKSK: "sk-SK",
  FIFI: "fi-FI",
  SvSE: "sv-SE",
  ViVN: "vi-VN",
  TRTR: "tr-TR",
  ElGR: "el-GR",
  RURU: "ru-RU",
  SrSP: "sr-SP",
  UkUA: "uk-UA",
  HyAM: "hy-AM",
  HeIL: "he-IL",
  UrPK: "ur-PK",
  ArSA: "ar-SA",
  HiIN: "hi-IN",
  THTH: "th-TH",
  KoKR: "ko-KR",
  JaJP: "ja-JP",
  ZhCN: "zh-CN",
  ZhTW: "zh-TW",
  Auto: "auto",
} as const;
/**
 * Locale for the generated video.
 */
export type PostSeriesLocale = ClosedEnum<typeof PostSeriesLocale>;

/**
 * Aspect ratio of the video. Not required for News videos.
 */
export const PostSeriesAspectRatio = {
  Nine16: "9:16",
  Sixteen9: "16:9",
  One1: "1:1",
} as const;
/**
 * Aspect ratio of the video. Not required for News videos.
 */
export type PostSeriesAspectRatio = ClosedEnum<typeof PostSeriesAspectRatio>;

export const TimeZone = {
  PacificPagoPago: "Pacific/Pago_Pago",
  AmericaAdak: "America/Adak",
  PacificHonolulu: "Pacific/Honolulu",
  PacificMarquesas: "Pacific/Marquesas",
  AmericaAnchorage: "America/Anchorage",
  AmericaTijuana: "America/Tijuana",
  AmericaLosAngeles: "America/Los_Angeles",
  AmericaPhoenix: "America/Phoenix",
  AmericaDenver: "America/Denver",
  AmericaGuatemala: "America/Guatemala",
  AmericaChicago: "America/Chicago",
  AmericaChihuahua: "America/Chihuahua",
  PacificEaster: "Pacific/Easter",
  AmericaMexicoCity: "America/Mexico_City",
  AmericaRegina: "America/Regina",
  AmericaBogota: "America/Bogota",
  AmericaCancun: "America/Cancun",
  AmericaNewYork: "America/New_York",
  AmericaPortAuPrince: "America/Port-au-Prince",
  AmericaHavana: "America/Havana",
  AmericaFortWayne: "America/Fort_Wayne",
  AmericaAsuncion: "America/Asuncion",
  AmericaHalifax: "America/Halifax",
  AmericaCaracas: "America/Caracas",
  AmericaCuiaba: "America/Cuiaba",
  AmericaLaPaz: "America/La_Paz",
  AmericaSantiago: "America/Santiago",
  AmericaGrandTurk: "America/Grand_Turk",
  AmericaStJohns: "America/St_Johns",
  AmericaAraguaina: "America/Araguaina",
  AmericaSaoPaulo: "America/Sao_Paulo",
  AmericaCayenne: "America/Cayenne",
  AmericaArgentinaBuenosAires: "America/Argentina/Buenos_Aires",
  AmericaGodthab: "America/Godthab",
  AmericaMontevideo: "America/Montevideo",
  AmericaMiquelon: "America/Miquelon",
  AmericaBahia: "America/Bahia",
  AmericaNoronha: "America/Noronha",
  AtlanticAzores: "Atlantic/Azores",
  AtlanticCapeVerde: "Atlantic/Cape_Verde",
  EuropeLondon: "Europe/London",
  AfricaAbidjan: "Africa/Abidjan",
  EuropeBerlin: "Europe/Berlin",
  EuropeBelgrade: "Europe/Belgrade",
  EuropeBrussels: "Europe/Brussels",
  AfricaLagos: "Africa/Lagos",
  AfricaCasablanca: "Africa/Casablanca",
  AfricaWindhoek: "Africa/Windhoek",
  EuropeBucharest: "Europe/Bucharest",
  AsiaBeirut: "Asia/Beirut",
  AfricaCairo: "Africa/Cairo",
  AsiaDamascus: "Asia/Damascus",
  AsiaGaza: "Asia/Gaza",
  AfricaMaputo: "Africa/Maputo",
  EuropeKiev: "Europe/Kiev",
  AsiaJerusalem: "Asia/Jerusalem",
  EuropeKaliningrad: "Europe/Kaliningrad",
  AfricaTripoli: "Africa/Tripoli",
  AsiaAmman: "Asia/Amman",
  AsiaBaghdad: "Asia/Baghdad",
  EuropeIstanbul: "Europe/Istanbul",
  AsiaRiyadh: "Asia/Riyadh",
  EuropeMinsk: "Europe/Minsk",
  EuropeMoscow: "Europe/Moscow",
  AfricaNairobi: "Africa/Nairobi",
  AsiaTehran: "Asia/Tehran",
  AsiaDubai: "Asia/Dubai",
  EuropeVolgograd: "Europe/Volgograd",
  AsiaBaku: "Asia/Baku",
  EuropeSamara: "Europe/Samara",
  IndianMauritius: "Indian/Mauritius",
  AsiaTbilisi: "Asia/Tbilisi",
  AsiaYerevan: "Asia/Yerevan",
  AsiaKabul: "Asia/Kabul",
  AsiaTashkent: "Asia/Tashkent",
  AsiaYekaterinburg: "Asia/Yekaterinburg",
  AsiaKarachi: "Asia/Karachi",
  AsiaAlmaty: "Asia/Almaty",
  AsiaKolkata: "Asia/Kolkata",
  AsiaColombo: "Asia/Colombo",
  AsiaKathmandu: "Asia/Kathmandu",
  AsiaDhaka: "Asia/Dhaka",
  AsiaRangoon: "Asia/Rangoon",
  AsiaNovosibirsk: "Asia/Novosibirsk",
  AsiaBangkok: "Asia/Bangkok",
  AsiaBarnaul: "Asia/Barnaul",
  AsiaHovd: "Asia/Hovd",
  AsiaKrasnoyarsk: "Asia/Krasnoyarsk",
  AsiaTomsk: "Asia/Tomsk",
  AsiaShanghai: "Asia/Shanghai",
  AsiaIrkutsk: "Asia/Irkutsk",
  AsiaKualaLumpur: "Asia/Kuala_Lumpur",
  AustraliaPerth: "Australia/Perth",
  AsiaTaipei: "Asia/Taipei",
  AsiaUlaanbaatar: "Asia/Ulaanbaatar",
  AsiaPyongyang: "Asia/Pyongyang",
  AustraliaEucla: "Australia/Eucla",
  AsiaChita: "Asia/Chita",
  AsiaTokyo: "Asia/Tokyo",
  AsiaSeoul: "Asia/Seoul",
  AsiaYakutsk: "Asia/Yakutsk",
  AustraliaAdelaide: "Australia/Adelaide",
  AustraliaDarwin: "Australia/Darwin",
  AustraliaBrisbane: "Australia/Brisbane",
  AustraliaSydney: "Australia/Sydney",
  PacificPortMoresby: "Pacific/Port_Moresby",
  AustraliaHobart: "Australia/Hobart",
  AsiaVladivostok: "Asia/Vladivostok",
  AustraliaLordHowe: "Australia/Lord_Howe",
  PacificBougainville: "Pacific/Bougainville",
  AsiaSrednekolymsk: "Asia/Srednekolymsk",
  AsiaMagadan: "Asia/Magadan",
  PacificNorfolk: "Pacific/Norfolk",
  AsiaSakhalin: "Asia/Sakhalin",
  PacificNoumea: "Pacific/Noumea",
  AsiaAnadyr: "Asia/Anadyr",
  PacificAuckland: "Pacific/Auckland",
  PacificFiji: "Pacific/Fiji",
  PacificChatham: "Pacific/Chatham",
  PacificTongatapu: "Pacific/Tongatapu",
  PacificApia: "Pacific/Apia",
  PacificKiritimati: "Pacific/Kiritimati",
} as const;
export type TimeZone = ClosedEnum<typeof TimeZone>;

export type Times = {
  dayOfWeek: number;
  timeOfDay: number;
};

/**
 * Publishing schedule for the video (optional).
 */
export type Schedule = {
  timeZone: TimeZone;
  times: Array<Times>;
};

export type Topics = {
  /**
   * Topic of each video in the series.
   */
  topic: string;
};

export type PostSeriesRequestBody = {
  contentType?: PostSeriesContentType | undefined;
  /**
   * Locale for the generated video.
   */
  locale?: PostSeriesLocale | undefined;
  /**
   * The ID of the image style to use. Use the [List image styles](#tag/images/GET/presets/{type}) endpoint to get a list of available image styles. If left empty, the AI chooses.
   */
  imageStyleId?: string | undefined;
  /**
   * List of publishing connection ids. Use the [List connections](#tag/connections/GET) endpoint to get a list of available connections
   */
  connectionIds: Array<string>;
  /**
   * Aspect ratio of the video. Not required for News videos.
   */
  aspectRatio?: PostSeriesAspectRatio | undefined;
  /**
   * Voice playback speed percentage.
   */
  voicePlaybackRate?: number | undefined;
  /**
   * Voice volume percentage.
   */
  voiceVolume?: number | undefined;
  /**
   * Soundtrack playback speed percentage.
   */
  soundtrackPlaybackRate?: number | undefined;
  /**
   * Soundtrack volume percentage.
   */
  soundtrackVolume?: number | undefined;
  /**
   * Publishing schedule for the video (optional).
   */
  schedule?: Schedule | undefined;
  /**
   * The desired video duration in seconds. Must be <= 900. Not required for news.
   */
  duration?: number | undefined;
  /**
   * Array of series topics.
   */
  topics?: Array<Topics> | undefined;
  /**
   * Base idea or theme for generating custom topics. Required for Custom and Quiz series
   */
  parentTopic?: string | undefined;
  /**
   * List of voice IDs to use. See the [List voices](#tag/voices/GET/voices) endpoint. If left empty, the AI chooses.
   */
  voiceIds?: Array<string> | undefined;
  /**
   * List of soundtrack IDs to use for background music. See the [List music](#tag/music/GET/music/genres) endpoint for available genres, and the [List music tracks](#tag/music/GET/music/tracks) endpoint for available soundtracks. If left empty, the AI chooses.
   */
  soundtrackIds?: Array<string> | undefined;
};

/** @internal */
export const PostSeriesContentType$inboundSchema: z.ZodNativeEnum<
  typeof PostSeriesContentType
> = z.nativeEnum(PostSeriesContentType);

/** @internal */
export const PostSeriesContentType$outboundSchema: z.ZodNativeEnum<
  typeof PostSeriesContentType
> = PostSeriesContentType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostSeriesContentType$ {
  /** @deprecated use `PostSeriesContentType$inboundSchema` instead. */
  export const inboundSchema = PostSeriesContentType$inboundSchema;
  /** @deprecated use `PostSeriesContentType$outboundSchema` instead. */
  export const outboundSchema = PostSeriesContentType$outboundSchema;
}

/** @internal */
export const PostSeriesLocale$inboundSchema: z.ZodNativeEnum<
  typeof PostSeriesLocale
> = z.nativeEnum(PostSeriesLocale);

/** @internal */
export const PostSeriesLocale$outboundSchema: z.ZodNativeEnum<
  typeof PostSeriesLocale
> = PostSeriesLocale$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostSeriesLocale$ {
  /** @deprecated use `PostSeriesLocale$inboundSchema` instead. */
  export const inboundSchema = PostSeriesLocale$inboundSchema;
  /** @deprecated use `PostSeriesLocale$outboundSchema` instead. */
  export const outboundSchema = PostSeriesLocale$outboundSchema;
}

/** @internal */
export const PostSeriesAspectRatio$inboundSchema: z.ZodNativeEnum<
  typeof PostSeriesAspectRatio
> = z.nativeEnum(PostSeriesAspectRatio);

/** @internal */
export const PostSeriesAspectRatio$outboundSchema: z.ZodNativeEnum<
  typeof PostSeriesAspectRatio
> = PostSeriesAspectRatio$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostSeriesAspectRatio$ {
  /** @deprecated use `PostSeriesAspectRatio$inboundSchema` instead. */
  export const inboundSchema = PostSeriesAspectRatio$inboundSchema;
  /** @deprecated use `PostSeriesAspectRatio$outboundSchema` instead. */
  export const outboundSchema = PostSeriesAspectRatio$outboundSchema;
}

/** @internal */
export const TimeZone$inboundSchema: z.ZodNativeEnum<typeof TimeZone> = z
  .nativeEnum(TimeZone);

/** @internal */
export const TimeZone$outboundSchema: z.ZodNativeEnum<typeof TimeZone> =
  TimeZone$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TimeZone$ {
  /** @deprecated use `TimeZone$inboundSchema` instead. */
  export const inboundSchema = TimeZone$inboundSchema;
  /** @deprecated use `TimeZone$outboundSchema` instead. */
  export const outboundSchema = TimeZone$outboundSchema;
}

/** @internal */
export const Times$inboundSchema: z.ZodType<Times, z.ZodTypeDef, unknown> = z
  .object({
    dayOfWeek: z.number(),
    timeOfDay: z.number(),
  });

/** @internal */
export type Times$Outbound = {
  dayOfWeek: number;
  timeOfDay: number;
};

/** @internal */
export const Times$outboundSchema: z.ZodType<
  Times$Outbound,
  z.ZodTypeDef,
  Times
> = z.object({
  dayOfWeek: z.number(),
  timeOfDay: z.number(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Times$ {
  /** @deprecated use `Times$inboundSchema` instead. */
  export const inboundSchema = Times$inboundSchema;
  /** @deprecated use `Times$outboundSchema` instead. */
  export const outboundSchema = Times$outboundSchema;
  /** @deprecated use `Times$Outbound` instead. */
  export type Outbound = Times$Outbound;
}

export function timesToJSON(times: Times): string {
  return JSON.stringify(Times$outboundSchema.parse(times));
}

export function timesFromJSON(
  jsonString: string,
): SafeParseResult<Times, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Times$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Times' from JSON`,
  );
}

/** @internal */
export const Schedule$inboundSchema: z.ZodType<
  Schedule,
  z.ZodTypeDef,
  unknown
> = z.object({
  timeZone: TimeZone$inboundSchema,
  times: z.array(z.lazy(() => Times$inboundSchema)),
});

/** @internal */
export type Schedule$Outbound = {
  timeZone: string;
  times: Array<Times$Outbound>;
};

/** @internal */
export const Schedule$outboundSchema: z.ZodType<
  Schedule$Outbound,
  z.ZodTypeDef,
  Schedule
> = z.object({
  timeZone: TimeZone$outboundSchema,
  times: z.array(z.lazy(() => Times$outboundSchema)),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Schedule$ {
  /** @deprecated use `Schedule$inboundSchema` instead. */
  export const inboundSchema = Schedule$inboundSchema;
  /** @deprecated use `Schedule$outboundSchema` instead. */
  export const outboundSchema = Schedule$outboundSchema;
  /** @deprecated use `Schedule$Outbound` instead. */
  export type Outbound = Schedule$Outbound;
}

export function scheduleToJSON(schedule: Schedule): string {
  return JSON.stringify(Schedule$outboundSchema.parse(schedule));
}

export function scheduleFromJSON(
  jsonString: string,
): SafeParseResult<Schedule, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Schedule$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Schedule' from JSON`,
  );
}

/** @internal */
export const Topics$inboundSchema: z.ZodType<Topics, z.ZodTypeDef, unknown> = z
  .object({
    topic: z.string(),
  });

/** @internal */
export type Topics$Outbound = {
  topic: string;
};

/** @internal */
export const Topics$outboundSchema: z.ZodType<
  Topics$Outbound,
  z.ZodTypeDef,
  Topics
> = z.object({
  topic: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Topics$ {
  /** @deprecated use `Topics$inboundSchema` instead. */
  export const inboundSchema = Topics$inboundSchema;
  /** @deprecated use `Topics$outboundSchema` instead. */
  export const outboundSchema = Topics$outboundSchema;
  /** @deprecated use `Topics$Outbound` instead. */
  export type Outbound = Topics$Outbound;
}

export function topicsToJSON(topics: Topics): string {
  return JSON.stringify(Topics$outboundSchema.parse(topics));
}

export function topicsFromJSON(
  jsonString: string,
): SafeParseResult<Topics, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Topics$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Topics' from JSON`,
  );
}

/** @internal */
export const PostSeriesRequestBody$inboundSchema: z.ZodType<
  PostSeriesRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  content_type: PostSeriesContentType$inboundSchema.default("Custom"),
  locale: PostSeriesLocale$inboundSchema.default("auto"),
  image_style_id: z.string().optional(),
  connection_ids: z.array(z.string()),
  aspect_ratio: PostSeriesAspectRatio$inboundSchema.default("9:16"),
  voice_playback_rate: z.number().default(100),
  voice_volume: z.number().default(100),
  soundtrack_playback_rate: z.number().default(100),
  soundtrack_volume: z.number().default(100),
  schedule: z.lazy(() => Schedule$inboundSchema).optional(),
  duration: z.number().optional(),
  topics: z.array(z.lazy(() => Topics$inboundSchema)).optional(),
  parent_topic: z.string().optional(),
  voice_ids: z.array(z.string()).optional(),
  soundtrack_ids: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "content_type": "contentType",
    "image_style_id": "imageStyleId",
    "connection_ids": "connectionIds",
    "aspect_ratio": "aspectRatio",
    "voice_playback_rate": "voicePlaybackRate",
    "voice_volume": "voiceVolume",
    "soundtrack_playback_rate": "soundtrackPlaybackRate",
    "soundtrack_volume": "soundtrackVolume",
    "parent_topic": "parentTopic",
    "voice_ids": "voiceIds",
    "soundtrack_ids": "soundtrackIds",
  });
});

/** @internal */
export type PostSeriesRequestBody$Outbound = {
  content_type: string;
  locale: string;
  image_style_id?: string | undefined;
  connection_ids: Array<string>;
  aspect_ratio: string;
  voice_playback_rate: number;
  voice_volume: number;
  soundtrack_playback_rate: number;
  soundtrack_volume: number;
  schedule?: Schedule$Outbound | undefined;
  duration?: number | undefined;
  topics?: Array<Topics$Outbound> | undefined;
  parent_topic?: string | undefined;
  voice_ids?: Array<string> | undefined;
  soundtrack_ids?: Array<string> | undefined;
};

/** @internal */
export const PostSeriesRequestBody$outboundSchema: z.ZodType<
  PostSeriesRequestBody$Outbound,
  z.ZodTypeDef,
  PostSeriesRequestBody
> = z.object({
  contentType: PostSeriesContentType$outboundSchema.default("Custom"),
  locale: PostSeriesLocale$outboundSchema.default("auto"),
  imageStyleId: z.string().optional(),
  connectionIds: z.array(z.string()),
  aspectRatio: PostSeriesAspectRatio$outboundSchema.default("9:16"),
  voicePlaybackRate: z.number().default(100),
  voiceVolume: z.number().default(100),
  soundtrackPlaybackRate: z.number().default(100),
  soundtrackVolume: z.number().default(100),
  schedule: z.lazy(() => Schedule$outboundSchema).optional(),
  duration: z.number().optional(),
  topics: z.array(z.lazy(() => Topics$outboundSchema)).optional(),
  parentTopic: z.string().optional(),
  voiceIds: z.array(z.string()).optional(),
  soundtrackIds: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    contentType: "content_type",
    imageStyleId: "image_style_id",
    connectionIds: "connection_ids",
    aspectRatio: "aspect_ratio",
    voicePlaybackRate: "voice_playback_rate",
    voiceVolume: "voice_volume",
    soundtrackPlaybackRate: "soundtrack_playback_rate",
    soundtrackVolume: "soundtrack_volume",
    parentTopic: "parent_topic",
    voiceIds: "voice_ids",
    soundtrackIds: "soundtrack_ids",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostSeriesRequestBody$ {
  /** @deprecated use `PostSeriesRequestBody$inboundSchema` instead. */
  export const inboundSchema = PostSeriesRequestBody$inboundSchema;
  /** @deprecated use `PostSeriesRequestBody$outboundSchema` instead. */
  export const outboundSchema = PostSeriesRequestBody$outboundSchema;
  /** @deprecated use `PostSeriesRequestBody$Outbound` instead. */
  export type Outbound = PostSeriesRequestBody$Outbound;
}

export function postSeriesRequestBodyToJSON(
  postSeriesRequestBody: PostSeriesRequestBody,
): string {
  return JSON.stringify(
    PostSeriesRequestBody$outboundSchema.parse(postSeriesRequestBody),
  );
}

export function postSeriesRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostSeriesRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostSeriesRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostSeriesRequestBody' from JSON`,
  );
}
