openapi: 3.1.0
info:
  title: ShortGenius API
  version: 1.0.0
servers:
  - url: https://shortgenius.com/api/v1
components:
  schemas: {}
  parameters: {}
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - ok
                required:
                  - status
      x-speakeasy-group: status
      x-speakeasy-name-override: check
webhooks: {}
