/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DraftScene,
  DraftScene$inboundSchema,
  DraftScene$Outbound,
  DraftScene$outboundSchema,
} from "./draftscene.js";

export type DraftVideo = {
  /**
   * The title of the video.
   */
  title: string;
  /**
   * The description shown beside the video when posted to social media.
   */
  caption: string;
  scenes: Array<DraftScene>;
};

/** @internal */
export const DraftVideo$inboundSchema: z.ZodType<
  DraftVideo,
  z.ZodTypeDef,
  unknown
> = z.object({
  title: z.string(),
  caption: z.string(),
  scenes: z.array(DraftScene$inboundSchema),
});

/** @internal */
export type DraftVideo$Outbound = {
  title: string;
  caption: string;
  scenes: Array<DraftScene$Outbound>;
};

/** @internal */
export const DraftVideo$outboundSchema: z.ZodType<
  DraftVideo$Outbound,
  z.ZodTypeDef,
  DraftVideo
> = z.object({
  title: z.string(),
  caption: z.string(),
  scenes: z.array(DraftScene$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DraftVideo$ {
  /** @deprecated use `DraftVideo$inboundSchema` instead. */
  export const inboundSchema = DraftVideo$inboundSchema;
  /** @deprecated use `DraftVideo$outboundSchema` instead. */
  export const outboundSchema = DraftVideo$outboundSchema;
  /** @deprecated use `DraftVideo$Outbound` instead. */
  export type Outbound = DraftVideo$Outbound;
}

export function draftVideoToJSON(draftVideo: DraftVideo): string {
  return JSON.stringify(DraftVideo$outboundSchema.parse(draftVideo));
}

export function draftVideoFromJSON(
  jsonString: string,
): SafeParseResult<DraftVideo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DraftVideo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DraftVideo' from JSON`,
  );
}
